#!/bin/bash

echo Running code generation
echo ...
flutter pub run build_runner --delete-conflicting-outputs "$1" \
--build-filter 'package:cloudflare_sdk/src/entity/*.dart' \
--build-filter 'package:cloudflare_sdk/src/service/*.dart' \
"$2" "$3" "$4" "$5"
