name: cloudflare_sdk
description: This is a flutter package for Cloudflare media API.
version: 0.0.1+1
homepage: https://github.com/luis901101/cloudflare-sdk

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
  retrofit: ^3.0.0
  http: ^0.13.4
  dio: ^4.0.4
  http_parser: ^4.0.0
  meta: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7 #flutter pub run build_runner build

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
