name: cloudflare
description: This is a dart package for Cloudflare API to allow easy Image, Stream and Live Input api management.
version: 1.3.1+12
homepage: https://github.com/luis901101/cloudflare

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  json_annotation: ^4.5.0
  retrofit: ^3.0.0
  http: ^0.13.4
  dio: ^4.0.4
  cross_file: ^0.3.3
  path: ^1.0.0
  tusc: ^1.0.0
#    path: ../tusc
  meta: ^1.0.0
  copy_with_extension: ^4.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+1
  copy_with_extension_gen: ^4.0.3
  build_runner: ^2.2.0 #flutter pub run build_runner build
