name: cloudflare
description: This is a flutter package for Cloudflare media API.
version: 0.0.1+2
homepage: https://github.com/luis901101/cloudflare

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  retrofit: ^3.0.0
  http: ^0.13.4
  dio: ^4.0.4
  http_parser: ^4.0.0
  meta: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7 #flutter pub run build_runner build
