import 'package:cloudflare/src/utils/jsonable.dart';
import 'package:copy_with_extension/copy_with_extension.dart';
import 'package:json_annotation/json_annotation.dart';

part 'r2_signed_url.g.dart';

/// A presigned S3/R2 URL that grants temporary, credential-free access to a
/// specific R2 object.
///
/// Generated by [R2API.presignedUrl]; share [url] with a client so
/// it can read or write an object without needing its own R2 credentials.
///
/// Example – client-side upload flow:
/// ```dart
/// // Backend: generate a presigned PUT URL valid for 15 minutes.
/// final signed = await r2.presignedUrl(
///   'my-bucket', 'uploads/document.pdf',
///   method: AWSHttpMethod.put,
///   expiresIn: Duration(minutes: 15),
/// );
///
/// // Client: upload without credentials.
/// await http.put(
///   Uri.parse(signed.url),
///   headers: {'content-type': 'application/pdf'},
///   body: pdfBytes,
/// );
/// ```
@CopyWith()
@JsonSerializable()
class R2SignedUrl extends Jsonable<R2SignedUrl> {
  /// The full presigned URL string.
  ///
  /// Pass this to an HTTP client to access the object without any additional
  /// authentication headers. The URL embeds SigV4 credentials in its query
  /// parameters and is only valid until [expiresAt].
  final String url;

  /// The R2 bucket the object lives in.
  final String bucket;

  /// The object key within [bucket] (analogous to a file path).
  final String key;

  /// The HTTP method this URL permits — uppercase, e.g. `"GET"` or `"PUT"`.
  ///
  /// A `"GET"` URL is used for downloads; a `"PUT"` URL allows client-side
  /// uploads directly to R2 without credentials.
  final String type;

  /// The UTC instant at which the presigned URL expires.
  ///
  /// Computed locally as `DateTime.now().toUtc().add(expiresIn)` at the moment
  /// the URL is generated; it is an approximation (network round-trip time is
  /// not accounted for).
  final DateTime expiresAt;

  const R2SignedUrl({
    required this.url,
    required this.bucket,
    required this.key,
    required this.type,
    required this.expiresAt,
  });

  /// Whether the URL is still valid at the current instant.
  bool get isExpired => DateTime.now().toUtc().isAfter(expiresAt);

  factory R2SignedUrl.fromJson(Map<String, dynamic> json) =>
      _$R2SignedUrlFromJson(json);

  @override
  R2SignedUrl? fromJsonMap(Map<String, dynamic>? json) =>
      json != null ? R2SignedUrl.fromJson(json) : null;

  @override
  Map<String, dynamic> toJson() => _$R2SignedUrlToJson(this);
}
